services:
  bun:
    build: .
    command: bun /app/server.ts
    env_file:
      - path: ./.env
        required: false
    ports:
      - "9595:9595"
    volumes:
      - /opt/tekrop/shooting-stars/uploads:/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://0.0.0.0:9595 || exit 1"]
      interval: 5s
      timeout: 5s

  bun-dev:
    build:
      context: .
      target: dev
    env_file:
      - path: ./.env
        required: false
    ports:
      - "9595:9595"
    volumes:
      - /opt/tekrop/shooting-stars/uploads:/app/uploads
      - ./server.ts:/app/server.ts
      - ./index.html:/app/index.html
      - ./tsconfig.json:/app/tsconfig.json
      - ./biome.json:/app/biome.json
      - ./.gitignore:/app/.gitignore
      - ./src:/app/src
      - ./public:/app/public
    profiles:
      - dev
